linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam
    - prealloc

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/helmedeiros/digital-asset-capitalization
  revive:
    min-confidence: 0.8

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - testutil
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
