linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/helmedeiros/digital-asset-capitalization

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - testutil

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
