format: dots
hide-summary: false
json: false
no-color: false
packages: ./...
parallel: true
post-run-command: ""
rerun-fails: false
rerun-fails-max-failures: 10
rerun-fails-max-runs: 3
rerun-fails-report: ""
rerun-fails-timeout: 0s
skip-missing: false
stdin: false
test-bench: false
test-benchmem: false
test-count: 1
test-cover: true
test-race: false
test-shuffle: false
test-timeout: 0s
test-v: false
watch: false
