name: CI

# Workflow to run tests and update coverage badge
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        id: test
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | tee coverage.txt
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 14

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

      - name: Run linter
        run: golangci-lint run

      - name: Update coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f811420c5b31e6c4d54855df77a88527
          filename: go-coverage.json
          label: coverage
          message: ${{ steps.test.outputs.coverage }}%
          color: green
