name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        env:
          JIRA_BASE_URL: "https://test.atlassian.net"
          JIRA_USERNAME: "test@example.com"
          JIRA_API_TOKEN: "test-token"
        run: go test -v ./...

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

      - name: Run linter
        run: golangci-lint run
